In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../../data/Ames_final_df_final.csv')

In [3]:
df.head()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,65.0,8450,7,5,2003,2003,196.0,706,0,150,...,False,False,False,False,True,False,False,False,True,False
1,80.0,9600,6,8,1976,1976,0.0,978,0,284,...,False,False,False,False,True,False,False,False,True,False
2,68.0,11250,7,5,2001,2002,162.0,486,0,434,...,False,False,False,False,True,False,False,False,True,False
3,60.0,9550,7,5,1915,1970,0.0,216,0,540,...,False,False,False,False,True,False,False,False,False,False
4,84.0,14260,8,5,2000,2000,350.0,655,0,490,...,False,False,False,False,True,False,False,False,True,False

In [5]:
missing = df.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1455 entries, 0 to 1454
Columns: 245 entries, LotFrontage to SaleCondition_Partial
dtypes: bool(209), float64(3), int64(33)
memory usage: 706.3 KB

In [8]:
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=51)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(X_train)

StandardScaler()

In [14]:
X_train_scaled = scaler.transform(X_train)

In [15]:
X_test_scaled = scaler.transform(X_test)

In [16]:
from sklearn.linear_model import ElasticNet

In [17]:
model = ElasticNet(max_iter=1000000)

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
grid_param = {'alpha':[0.1, 1, 5, 10, 50, 100], 'l1_ratio':[0.1, 0.3, 0.5, 0.8, 0.95, 0.99, 1]}

In [21]:
grid_model = GridSearchCV(estimator=model, 
                          param_grid=grid_param,
                          scoring='neg_mean_squared_error',
                          cv=10,
                          verbose=1)

In [22]:
grid_model.fit(X_train_scaled, y_train)

Fitting 10 folds for each of 42 candidates, totalling 420 fits

GridSearchCV(cv=10, estimator=ElasticNet(max_iter=1000000),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.8, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=1)

In [23]:
grid_model.best_estimator_

ElasticNet(alpha=10, l1_ratio=0.99, max_iter=1000000)

In [25]:
results = pd.DataFrame(grid_model.cv_results_)

In [27]:
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.085165,0.055167,0.001210,0.000685,0.1,0.10,"{'alpha': 0.1, 'l1_ratio': 0.1}",-5.277034e+08,-8.561313e+08,-8.095093e+08,-6.542270e+08,-5.282360e+08,-3.367003e+08,-4.106767e+08,-6.334349e+08,-4.235362e+08,-6.039932e+08,-5.784148e+08,1.598746e+08,2
1,0.061586,0.005617,0.001060,0.000166,0.1,0.30,"{'alpha': 0.1, 'l1_ratio': 0.3}",-5.219780e+08,-8.518319e+08,-8.137794e+08,-6.524725e+08,-5.256282e+08,-3.431819e+08,-4.171905e+08,-6.332933e+08,-4.397285e+08,-6.013950e+08,-5.800479e+08,1.567432e+08,3
2,0.076871,0.005240,0.000968,0.000113,0.1,0.50,"{'alpha': 0.1, 'l1_ratio': 0.5}",-5.173469e+08,-8.497830e+08,-8.225135e+08,-6.508863e+08,-5.244801e+08,-3.541192e+08,-4.266464e+08,-6.329941e+08,-4.636274e+08,-5.976985e+08,-5.840095e+08,1.531898e+08,6
3,0.132165,0.009510,0.000889,0.000017,0.1,0.80,"{'alpha': 0.1, 'l1_ratio': 0.8}",-5.155498e+08,-8.592328e+08,-8.525814e+08,-6.484460e+08,-5.292371e+08,-3.892226e+08,-4.516476e+08,-6.309244e+08,-5.353088e+08,-5.893341e+08,-6.001485e+08,1.473688e+08,10
4,0.456818,0.031528,0.000977,0.000124,0.1,0.95,"{'alpha': 0.1, 'l1_ratio': 0.95}",-5.197825e+08,-8.831429e+08,-8.913897e+08,-6.470322e+08,-5.387544e+08,-4.299230e+08,-4.795479e+08,-6.277602e+08,-6.251501e+08,-5.858736e+08,-6.228357e+08,1.474105e+08,13

In [28]:
y_predicitons = grid_model.predict(X_test_scaled)

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [33]:
print(f"mae: {mean_absolute_error(y_test, y_predicitons)}")
print(f"mse: {np.sqrt(mean_squared_error(y_test, y_predicitons))}")

mae: 16054.70067709026
mse: 22033.48892767387

In [ ]:
)